version: '3.8'

services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor/
    depends_on:
      - db
    container_name: web

  db:
    platform: "linux/amd64"
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    container_name: db

volumes:
  dbdata:
  vendor:

